# Generated by Django 3.1.5 on 2021-01-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vest_v3', '0002_auto_20210106_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='test-product'),
            preserve_default=False,
        ),
    ]
