# Generated by Django 3.1.5 on 2021-01-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vest_v3', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is a test description ksdkdfjsdlfdsfjslf lfsdfjlsfj;df sehfkjshdfkjsdhfjdh '),
            preserve_default=False,
        ),
    ]
